In [1]:
import pandas as pd

df = pd.DataFrame([
    [1, '3 inch screw', 0.50, 0.75],
    [2, '2 inch nail', 0.10, 0.25],
    [3, 'hammer', 3.00, 5.50],
    [4, 'screwdriver', 2.50, 3.00]
], columns=['Product ID', 'Product Description', 'Cost to Manufacture', 'Price'])

In [2]:
df['Sold in Bulk?'] = ['Yes', 'Yes', 'No', 'No']
df

   Product ID Product Description  Cost to Manufacture  Price Sold in Bulk?
0           1        3 inch screw                  0.5   0.75           Yes
1           2         2 inch nail                  0.1   0.25           Yes
2           3              hammer                  3.0   5.50            No
3           4         screwdriver                  2.5   3.00            No

In [3]:
df['In Stock?'] = True
df

,Product ID,Product Description,Cost to Manufacture,Price,Sold in Bulk?,In Stock?
0,1,3 inch screw,0.5,0.75,Yes,True
1,2,2 inch nail,0.1,0.25,Yes,True
2,3,hammer,3.0,5.50,No,True
3,4,screwdriver,2.5,3.00,No,True

In [4]:
df['Is taxed?'] = 'Yes'
df

,Product ID,Product Description,Cost to Manufacture,Price,Sold in Bulk?,In Stock?,Is taxed?
0,1,3 inch screw,0.5,0.75,Yes,True,Yes
1,2,2 inch nail,0.1,0.25,Yes,True,Yes
2,3,hammer,3.0,5.50,No,True,Yes
3,4,screwdriver,2.5,3.00,No,True,Yes

In [5]:
df['Sales Tax'] = df.Price * 0.075
df

,Product ID,Product Description,Cost to Manufacture,Price,Sold in Bulk?,In Stock?,Is taxed?,Sales Tax
0,1,3 inch screw,0.5,0.75,Yes,True,Yes,0.05625
1,2,2 inch nail,0.1,0.25,Yes,True,Yes,0.01875
2,3,hammer,3.0,5.50,No,True,Yes,0.41250
3,4,screwdriver,2.5,3.00,No,True,Yes,0.22500

In [6]:
df['Margin'] = df.Price - df['Cost to Manufacture']
df

,Product ID,Product Description,Cost to Manufacture,Price,Sold in Bulk?,In Stock?,Is taxed?,Sales Tax,Margin
0,1,3 inch screw,0.5,0.75,Yes,True,Yes,0.05625,0.25
1,2,2 inch nail,0.1,0.25,Yes,True,Yes,0.01875,0.15
2,3,hammer,3.0,5.50,No,True,Yes,0.41250,2.50
3,4,screwdriver,2.5,3.00,No,True,Yes,0.22500,0.50

In [7]:
df = pd.DataFrame([
    ['JOHN SMITH', 'john.smith@gmail.com'],
    ['Jane Doe', 'jdoe@yahoo.com'],
    ['joe schmo', 'joeschmo@hotmail.com']
], columns=['Name', 'Email'])

df['Lowercase Name'] = df.Name.apply(str.lower)
df

         Name                 Email Lowercase Name
0  JOHN SMITH  john.smith@gmail.com     john smith
1    Jane Doe        jdoe@yahoo.com       jane doe
2   joe schmo  joeschmo@hotmail.com      joe schmo