In [1]:
import pandas as pd

df = pd.DataFrame([
    ['John Smith', 15, 40],
    ['Jane Doe', 20, 43],
    ['Joe Schmo', 10, 35]
], columns=['name', 'hourly_wage', 'hours_worked'])

In [2]:
mylambda = lambda x: x[0] + x[-1]
print(mylambda('This is a string'))

Tg

In [4]:
mylambda = lambda age: "Добро пожаловать в BattleCity!" if age >= 13 else "Вам должно быть больше 13 лет"
mylambda(14)

'Добро пожаловать в BattleCity!'

In [7]:
get_last_name = lambda x: x.split(' ')[-1]
df['last_name'] = df.name.apply(get_last_name)
df

         name  hourly_wage  hours_worked last_name
0  John Smith           15            40     Smith
1    Jane Doe           20            43       Doe
2   Joe Schmo           10            35     Schmo

In [11]:
total_earned = lambda row: (row.hours_worked * row.hourly_wage) if row.hours_worked <= 40 else (40 * row.hourly_wage + (row.hours_worked - 40) * row.hourly_wage * 1.5)

df['total_earned'] = df.apply(total_earned, axis=1)
df

         name  hourly_wage  hours_worked last_name  total_earned
0  John Smith           15            40     Smith         600.0
1    Jane Doe           20            43       Doe         890.0
2   Joe Schmo           10            35     Schmo         350.0