In [1]:
import pandas as pd

df = pd.DataFrame([
    ['January', 100, 100, 23, 100],
    ['February', 51, 45, 145, 45],
    ['March', 81, 96, 65, 96],
    ['April', 80, 80, 54, 180],
    ['May', 51, 54, 54, 154],
    ['June', 112, 109, 79, 129]
], columns=['month', 'clinic_east', 'clinic_north', 'clinic_south', 'clinic_west'])

In [2]:
april_may_june = df.iloc[3:6]
april_may_june

   month  clinic_east  clinic_north  clinic_south  clinic_west
3  April           80            80            54          180
4    May           51            54            54          154
5   June          112           109            79          129

In [3]:
january = df[df.month == 'January']
january

     month  clinic_east  clinic_north  clinic_south  clinic_west
0  January          100           100            23          100

In [4]:
march_april = df[(df.month == 'March') | (df.month == 'April')]
march_april

   month  clinic_east  clinic_north  clinic_south  clinic_west
2  March           81            96            65           96
3  April           80            80            54          180

In [5]:
january_february_march = df[df.month.isin(['January', 'February', 'March'])]
january_february_march

      month  clinic_east  clinic_north  clinic_south  clinic_west
0   January          100           100            23          100
1  February           51            45           145           45
2     March           81            96            65           96

In [6]:
df2 = df[df.month.isin(['January', 'March', 'May'])].copy()
df2

     month  clinic_east  clinic_north  clinic_south  clinic_west
0  January          100           100            23          100
2    March           81            96            65           96
4      May           51            54            54          154

In [7]:
df3 = df2.reset_index()
df3

   index    month  clinic_east  clinic_north  clinic_south  clinic_west
0      0  January          100           100            23          100
1      2    March           81            96            65           96
2      4      May           51            54            54          154

In [8]:
df2.reset_index(inplace=True, drop=True)
df2

     month  clinic_east  clinic_north  clinic_south  clinic_west
0  January          100           100            23          100
1    March           81            96            65           96
2      May           51            54            54          154

In [9]:
orders = pd.read_csv('shoefly.csv', delimiter='\t')


emails = orders.email

frances_palmer = orders[(orders.first_name == 'Frances') & (orders.last_name == 'Palmer')]

comfy_shoes = orders[orders.shoe_type.isin(['clogs', 'boots', 'ballet flats'])]
orders.head()

,id,first_name,last_name,email,shoe_type,shoe_material,shoe_color
0,54791,Rebecca,Lindsay,RebeccaLindsay57@hotmail.com,clogs,faux-leather,black
1,53450,Emily,Joyce,EmilyJoyce25@gmail.com,ballet FLATs,faux-leather,navy
2,91987,Joyce,Waller,Joyce.Waller@gmail.com,sandals,fabric,black
3,14437,Justin,Erickson,Justin.Erickson@outlook.com,clogs,faux-leather,red
4,79357,Andrew,Banks,AB4318@gmail.com,boots,leather,brown

In [10]:
frances_palmer

,id,first_name,last_name,email,shoe_type,shoe_material,shoe_color
9,62083,Frances,Palmer,FrancesPalmer50@gmail.com,wedges,leather,white

In [11]:
comfy_shoes

,id,first_name,last_name,email,shoe_type,shoe_material,shoe_color
0,54791,Rebecca,Lindsay,RebeccaLindsay57@hotmail.com,clogs,faux-leather,black
3,14437,Justin,Erickson,Justin.Erickson@outlook.com,clogs,faux-leather,red
4,79357,Andrew,Banks,AB4318@gmail.com,boots,leather,brown
6,20487,Thomas,Jensen,TJ5470@gmail.com,clogs,fabric,navy
7,76971,Janice,Hicks,Janice.Hicks@gmail.com,clogs,faux-leather,navy
8,21586,Gabriel,Porter,GabrielPorter24@gmail.com,clogs,leather,brown
10,91629,Jessica,Hale,JessicaHale25@gmail.com,clogs,leather,red
12,45832,Susan,Dennis,SusanDennis58@gmail.com,ballet flats,fabric,white
14,73431,Rebecca,Charles,Rebecca.Charles@gmail.com,boots,faux-leather,white
16,39888,Vincent,Stephenson,VS4753@outlook.com,boots,leather,black
17,35961,Roy,Tillman,RoyTillman20@gmail.com,boots,leather,white