In [1]:
import pandas as pd

df1 = pd.read_csv('df1.csv', delimiter='\t')
df2 = pd.read_csv('df2.csv', delimiter='\t')

clean = 1

## Head DF1

In [2]:
df1.head()

   Unnamed: 0 Grocery Item  Cake Recipe  Pancake Recipe  Cookie Recipe
0           0         Eggs            2               3              1
1           1         Milk            1               2              1
2           2        Flour            2               1              2

## Head DF2

In [3]:
df2.head()

   Unnamed: 0 Grocery Item          Recipe  Number
0           0         Eggs     Cake Recipe       2
1           1         Milk     Cake Recipe       1
2           2        Flour     Cake Recipe       2
3           3         Eggs  Pancake Recipe       3
4           4         Milk  Pancake Recipe       2

## Info DF1

In [4]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      3 non-null      int64
 1   Grocery Item    3 non-null      str
 2   Cake Recipe     3 non-null      int64
 3   Pancake Recipe  3 non-null      int64
 4   Cookie Recipe   3 non-null      int64
dtypes: int64(4), str(1)
memory usage: 252.0 bytes

## Info DF2

In [5]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    9 non-null      int64
 1   Grocery Item  9 non-null      str
 2   Recipe        9 non-null      str
 3   Number        9 non-null      int64
dtypes: int64(2), str(2)
memory usage: 420.0 bytes

In [6]:
df1.describe()

       Unnamed: 0  Cake Recipe  Pancake Recipe  Cookie Recipe
count         3.0     3.000000             3.0       3.000000
mean          1.0     1.666667             2.0       1.333333
std           1.0     0.577350             1.0       0.577350
min           0.0     1.000000             1.0       1.000000
25%           0.5     1.500000             1.5       1.000000
50%           1.0     2.000000             2.0       1.000000
75%           1.5     2.000000             2.5       1.500000
max           2.0     2.000000             3.0       2.000000

In [7]:
df2.describe()

       Unnamed: 0    Number
count    9.000000  9.000000
mean     4.000000  1.666667
std      2.738613  0.707107
min      0.000000  1.000000
25%      2.000000  1.000000
50%      4.000000  2.000000
75%      6.000000  2.000000
max      8.000000  3.000000

In [8]:
df1.columns

Index(['Unnamed: 0', 'Grocery Item', 'Cake Recipe', 'Pancake Recipe',
       'Cookie Recipe'],
      dtype='str')

In [9]:
df2.columns

Index(['Unnamed: 0', 'Grocery Item', 'Recipe', 'Number'], dtype='str')

In [10]:
import glob

student_files = glob.glob("stud*.csv")

df_list = []
for filename in student_files:
    data = pd.read_csv(filename, delimiter='\t')
    df_list.append(data)

students = pd.concat(df_list)

students

,Unnamed: 0,full_name,gender_age,fractions,probability,grade,exam,score
0,5,Eldin Spitell,M16,NaN,83%,11th grade,NaN,NaN
1,6,Christi Lesser,F17,86%,84%,9th grade,NaN,NaN
2,7,Papageno Rummin,M17,81%,77%,11th grade,NaN,NaN
3,8,Nissa Wrotchford,F18,68%,75%,12th grade,NaN,NaN
4,9,Vincent Blumer,M14,59%,NaN,11th grade,NaN,NaN
...,...,...,...,...,...,...,...,...
0,0,Moses Kirckman,M14,69%,89%,11th grade,NaN,NaN
1,1,Timofei Strowan,M18,63%,76%,11th grade,NaN,NaN
2,2,Silvain Poll,M18,69%,77%,9th grade,NaN,NaN
3,3,Lezley Pinxton,M18,NaN,72%,11th grade,NaN,NaN
4,4,Bernadene Saunper,F17,72%,84%,11th grade,NaN,NaN

In [11]:
students.shape

(2010, 8)

In [12]:
duplicates = students.duplicated()
print(duplicates.value_counts())

students = students.drop_duplicates()

duplicates = students.duplicated()
duplicates.value_counts()

False    2010
Name: count, dtype: int64

False    2010
Name: count, dtype: int64

In [13]:
print(students.columns)
print(students.gender_age.head())

students['gender'] = students.gender_age.str[0]
students['age'] = students.gender_age.str[1:]
students.head()

Index(['Unnamed: 0', 'full_name', 'gender_age', 'fractions', 'probability',
       'grade', 'exam', 'score'],
      dtype='str')
0    M16
1    F17
2    M17
3    F18
4    M14
Name: gender_age, dtype: str

,Unnamed: 0,full_name,gender_age,fractions,probability,grade,exam,score,gender,age
0,5,Eldin Spitell,M16,NaN,83%,11th grade,NaN,NaN,M,16
1,6,Christi Lesser,F17,86%,84%,9th grade,NaN,NaN,F,17
2,7,Papageno Rummin,M17,81%,77%,11th grade,NaN,NaN,M,17
3,8,Nissa Wrotchford,F18,68%,75%,12th grade,NaN,NaN,F,18
4,9,Vincent Blumer,M14,59%,NaN,11th grade,NaN,NaN,M,14

In [14]:
students = students[['full_name', 'gender', 'age', 'score']]
students.head()

          full_name gender age score
0     Eldin Spitell      M  16   NaN
1    Christi Lesser      F  17   NaN
2   Papageno Rummin      M  17   NaN
3  Nissa Wrotchford      F  18   NaN
4    Vincent Blumer      M  14   NaN

In [15]:
name_split = students.full_name.str.split(' ')

students['first_name'] = name_split.str.get(0)
students['last_name'] = name_split.str.get(1)

students.head()

          full_name gender age score first_name   last_name
0     Eldin Spitell      M  16   NaN      Eldin     Spitell
1    Christi Lesser      F  17   NaN    Christi      Lesser
2   Papageno Rummin      M  17   NaN   Papageno      Rummin
3  Nissa Wrotchford      F  18   NaN      Nissa  Wrotchford
4    Vincent Blumer      M  14   NaN    Vincent      Blumer

In [16]:
students.dtypes

full_name        str
gender           str
age              str
score            str
first_name    object
last_name     object
dtype: object

In [17]:
students['score'] = students['score'].replace('[\%,]', '', regex=True)
students['score'] = pd.to_numeric(students.score)
students.score.mean()

<>:1: SyntaxWarning: "\%" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\%"? A raw string is also an option.
<>:1: SyntaxWarning: "\%" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\%"? A raw string is also an option.
/tmp/ipykernel_266476/934580288.py:1: SyntaxWarning: "\%" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\%"? A raw string is also an option.
  students['score'] = students['score'].replace('[\%,]', '', regex=True)

np.float64(77.73132724341751)

In [18]:
print(students['score'].head())

students['score'] = students['score'].replace('(\d+)', '', regex=True)

print(students.dtypes)

students['score'] = pd.to_numeric(students.score)

avg_grade = students.score.mean()
print(avg_grade)

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: score, dtype: float64
full_name         str
gender            str
age               str
score         float64
first_name     object
last_name      object
dtype: object
77.73132724341751

<>:3: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:3: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
/tmp/ipykernel_266476/1592298249.py:3: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  students['score'] = students['score'].replace('(\d+)', '', regex=True)

In [19]:
score_mean = students.score.mean()
print(score_mean)

students['score'] = students['score'].fillna(0)

score_mean_2 = students.score.mean()
print(score_mean_2)

77.73132724341751
71.96915422885571